In [ ]:
import numpy as np
import pandas as pd

import torch
from torch.utils.data import Dataset, DataLoader

# 创建dataframe
seq_l1 = [i for i in range(24)]
seq_f1 = [i + 100 for i in range(24)]
seq_f2 = [i + 200 for i in range(24)]
seq_f3 = [i + 300 for i in range(24)]
seq_f4 = [i + 400 for i in range(24)]
seq_f5 = [i + 500 for i in range(24)]
df = pd.DataFrame({
    'label': seq_l1,
    'f1': seq_f1,
    'f2': seq_f2,
    'f3': seq_f3,
    'f4': seq_f4,
    'f5': seq_f5
})

print("df shape: {}".format(df.shape))
print(df.head())

# ----------------------------------------------------------------------------------------------------------
# 构造Numpy数据集
# ----------------------------------------------------------------------------------------------------------
train_X = df.loc[:, ['f1', 'f2', 'f3', 'f4', 'f5']].values
train_y = df.loc[:, ['label']].values

print("train_X shape: {}".format(train_X.shape))
print("train_y shape: {}".format(train_y.shape))

print(train_X[:5])
print(train_y[:5])

# ----------------------------------------------------------------------------------------------------------
# 构造Pandas数据集
# ----------------------------------------------------------------------------------------------------------
class RushDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]
    
dataset_train = RushDataset(train_X, train_y)


# ----------------------------------------------------------------------------------------------------------
# 构造DataLoader
# ----------------------------------------------------------------------------------------------------------
dataloader_train = DataLoader(dataset_train, batch_size=2, shuffle=False, num_workers=0)

# 遍历DataLoader
for idx, (batch_X, batch_y) in enumerate(dataloader_train):
    print("idx: {}, batch_X: {}, batch_y: {}".format(idx, batch_X, batch_y))

df shape: (24, 6)
   label   f1   f2   f3   f4   f5
0      0  100  200  300  400  500
1      1  101  201  301  401  501
2      2  102  202  302  402  502
3      3  103  203  303  403  503
4      4  104  204  304  404  504
train_X shape: (24, 5)
train_y shape: (24, 1)
[[100 200 300 400 500]
 [101 201 301 401 501]
 [102 202 302 402 502]
 [103 203 303 403 503]
 [104 204 304 404 504]]
[[0]
 [1]
 [2]
 [3]
 [4]]
idx: 0, batch_X: tensor([[100, 200, 300, 400, 500],
        [101, 201, 301, 401, 501]]), batch_y: tensor([[0],
        [1]])
idx: 1, batch_X: tensor([[102, 202, 302, 402, 502],
        [103, 203, 303, 403, 503]]), batch_y: tensor([[2],
        [3]])
idx: 2, batch_X: tensor([[104, 204, 304, 404, 504],
        [105, 205, 305, 405, 505]]), batch_y: tensor([[4],
        [5]])
idx: 3, batch_X: tensor([[106, 206, 306, 406, 506],
        [107, 207, 307, 407, 507]]), batch_y: tensor([[6],
        [7]])
idx: 4, batch_X: tensor([[108, 208, 308, 408, 508],
        [109, 209, 309, 409, 509]]), b